FROM node:18-alpine

# Set the working directory
WORKDIR /app

# Install OpenSSL, which is needed by various packages on Alpine
RUN apk add --no-cache openssl

# Install nodemon globally
RUN npm install -g nodemon

# Copy package.json and package-lock.json (if available)
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application files
COPY . .

# Expose the port the app runs on
EXPOSE 3001

# Command to run the development server
CMD ["npm", "run", "dev"]
